export const newsApiCategories = [
  { value: 'general', label: 'General' },
  { value: 'business', label: 'Business' },
  { value: 'entertainment', label: 'Entertainment' },
  { value: 'health', label: 'Health' },
  { value: 'science', label: 'Science' },
  { value: 'sports', label: 'Sports' },
  { value: 'technology', label: 'Technology' },
];

export const nyTimesSections = [
  { label: 'Arts', value: 'Arts' },
  { label: 'Automobiles', value: 'Automobiles' },
  { label: 'Autos', value: 'Autos' },
  { label: 'Blogs', value: 'Blogs' },
  { label: 'Books', value: 'Books' },
  { label: 'Booming', value: 'Booming' },
  { label: 'Business', value: 'Business' },
  { label: 'Business Day', value: 'Business Day' },
  { label: 'Corrections', value: 'Corrections' },
  { label: 'Crosswords & Games', value: 'Crosswords & Games' },
  { label: 'Crosswords/Games', value: 'Crosswords/Games' },
  { label: 'Dining & Wine', value: 'Dining & Wine' },
  { label: 'Dining and Wine', value: 'Dining and Wine' },
  { label: "Editors' Notes", value: "Editors' Notes" },
  { label: 'Education', value: 'Education' },
  { label: 'Fashion & Style', value: 'Fashion & Style' },
  { label: 'Food', value: 'Food' },
  { label: 'Front Page', value: 'Front Page' },
  { label: 'Giving', value: 'Giving' },
  { label: 'Global Home', value: 'Global Home' },
  { label: 'Great Homes & Destinations', value: 'Great Homes & Destinations' },
  {
    label: 'Great Homes and Destinations',
    value: 'Great Homes and Destinations',
  },
  { label: 'Health', value: 'Health' },
  { label: 'Home & Garden', value: 'Home & Garden' },
  { label: 'Home and Garden', value: 'Home and Garden' },
  { label: 'International Home', value: 'International Home' },
  { label: 'Job Market', value: 'Job Market' },
  { label: 'Learning', value: 'Learning' },
  { label: 'Magazine', value: 'Magazine' },
  { label: 'Movies', value: 'Movies' },
  { label: 'Multimedia', value: 'Multimedia' },
  { label: 'Multimedia/Photos', value: 'Multimedia/Photos' },
  { label: 'N.Y. / Region', value: 'N.Y. / Region' },
  { label: 'N.Y./Region', value: 'N.Y./Region' },
  { label: 'NYRegion', value: 'NYRegion' },
  { label: 'NYT Now', value: 'NYT Now' },
  { label: 'National', value: 'National' },
  { label: 'New York', value: 'New York' },
  { label: 'New York and Region', value: 'New York and Region' },
  { label: 'Obituaries', value: 'Obituaries' },
  { label: 'Olympics', value: 'Olympics' },
  { label: 'Open', value: 'Open' },
  { label: 'Opinion', value: 'Opinion' },
  { label: 'Paid Death Notices', value: 'Paid Death Notices' },
  { label: 'Public Editor', value: 'Public Editor' },
  { label: 'Real Estate', value: 'Real Estate' },
  { label: 'Science', value: 'Science' },
  { label: 'Sports', value: 'Sports' },
  { label: 'Style', value: 'Style' },
  { label: 'Sunday Magazine', value: 'Sunday Magazine' },
  { label: 'Sunday Review', value: 'Sunday Review' },
  { label: 'T Magazine', value: 'T Magazine' },
  { label: 'T:Style', value: 'T:Style' },
  { label: 'Technology', value: 'Technology' },
  { label: 'The Public Editor', value: 'The Public Editor' },
  { label: 'The Upshot', value: 'The Upshot' },
  { label: 'Theater', value: 'Theater' },
  { label: 'Times Topics', value: 'Times Topics' },
  { label: 'TimesMachine', value: 'TimesMachine' },
  { label: "Today's Headlines", value: "Today's Headlines" },
  { label: 'Topics', value: 'Topics' },
  { label: 'Travel', value: 'Travel' },
  { label: 'U.S.', value: 'U.S.' },
  { label: 'Universal', value: 'Universal' },
  { label: 'UrbanEye', value: 'UrbanEye' },
  { label: 'Washington', value: 'Washington' },
  { label: 'Week in Review', value: 'Week in Review' },
  { label: 'World', value: 'World' },
  { label: 'Your Money', value: 'Your Money' },
];

export const guardianInitSections = [
  'culture',
  'community',
  'books',
  'fashion',
];

export const allApisFilters = [
  'q',
  'category',
  'section',
  'from-date',
  'to-date',
  'begin_date',
  'end_date',
  'fq',
  'page',
];
